Repository GatorCogitate/cogitate_tool, pull requests merged in 2020-02, with the labels that each got.

#25 Merge Dependencies Branch with Master
  .gitignore
  Pipfile
  Pipfile.lock
Labels: enhancement, formatting

#23 Merge database-integration with master
  data/demofile.json
  json_interaction/json_handler.py
  json_interaction/test_json_handler.py
Labels: enhancement, formatting

#39 Created Basic Folder Structure
  .gitignore
  data/README.md
  src/README.md
  src/cogitate_menu.py
  src/data_miner.py
  src/data_processor.py
  src/json_handler.py
  tests/README.md
  tests/test_json_handler.py
Labels: documentation, formatting

#43 Integrate/new-dependencies
  .gitignore
  Pipfile
  Pipfile.lock
Labels: dependencies

#46 Update to json_handler to make it more generalized
  src/json_handler.py
Labels: documentation, enhancement

#50 Merge functioning travis build into the travis branch
  .coveragerc
  .travis.yml
  Pipfile
  Pipfile.lock
  __init__.py
  scripts/cover.sh
  scripts/lint.sh
  scripts/test.sh
  src/__init__.py
  src/cogitate_menu.py
  src/data_miner.py
  src/data_processor.py
  src/json_handler.py
  tests/__init__.py
  tests/conftest.py
  tests/test_json_handler.py
Labels: enhancement, formatting, testing

#34 Prototype Issue/PR Retrieval
  .flake8
  .gitignore
  .pylintrc
  data/contributor_data_template.json
  data/demofile.json
  src/__init__.py
  src/cogitate.py
  src/data_collection.py
  tests/__init__.py
  tests/test_issue_retrieval.py
Labels: enhancement, testing
