Repository GatorCogitate/cogitate_tool, pull requests merged in 2020-03, with the labels that each got.

#31 Improve Travis CI configuration
  .codacy.yml
  .coveragerc
  .travis.yml
  Pipfile
  Pipfile.lock
  codecov.yml
  scripts/cover.bat
  scripts/cover.sh
  scripts/lint.bat
  scripts/lint.sh
  scripts/test.bat
  scripts/test.sh
  setup.cfg
  src/__init__.py
  src/data_collection.py
  src/data_processor.py
  src/json_handler.py
  tests/__init__.py
  tests/conftest.py
  tests/test_json_handler.py
Labels: important, testing

#58 Add/codecoverage
  .travis.yml
  codecov.yml
  scripts/cover.sh
Labels: enhancement

#35 Individual metrics lines
  .gitignore
  README.md
  data/contributor_data_template.json
  data/individual_metrics_testfile.json
  scripts/test.sh
  src/cogitate.py
  src/data_collection.py
  src/data_processor.py
  src/driller.py
  src/json_handler.py
  src/merge_duplicate_usernames.py
  tests/test_data_collection.py
  tests/test_issue_retrieval.py
  tests/test_json_handler.py
Labels: WIP, enhancement

#76 Multiple json files
  .gitignore
  data/individual_metrics_storage.json
  data/raw_data_storage.json
  src/data_collection.py
  tests/test_data_collection.py
Labels: enhancement

#70 Add updated README file
  README.md
  images/logo.png
Labels: documentation

#77 Individual metrics lines
  Pipfile.lock
  README.md
  data/contributor_data_template.json
  data/individual_metrics_testfile.json
  src/data_collection.py
  src/json_handler.py
  src/merge_duplicate_usernames.py
  tests/test_data_collection.py
  tests/test_json_handler.py
Labels: WIP, enhancement, formatting, important, testing

#71 Building and Testing: Features 1 & 2
  src/data_collection.py
  tests/test_data_collection.py
Labels: enhancement

#60 Command line interface
  CommandLineOutline.md
  Pipfile.lock
  README.md
  data/branch_info_input.txt
  data/contributor_data.json
  data/contributor_data_template.json
  src/cogitate.py
  src/data_collection.py
  src/driller.py
  tests/test_cogitate.py
Labels: WIP, documentation, important

#80 Merge Master into Command Line interface branch
  Pipfile.lock
  README.md
  data/contributor_data_template.json
  data/individual_metrics_testfile.json
  images/logo.png
  src/data_collection.py
  src/json_handler.py
  src/merge_duplicate_usernames.py
  tests/test_data_collection.py
  tests/test_json_handler.py
Labels: help wanted, important

#82 Revert "Command line interface"
  CommandLineOutline.md
  Pipfile.lock
  README.md
  data/branch_info_input.txt
  data/contributor_data.json
  data/contributor_data_template.json
  src/cogitate.py
  src/data_collection.py
  src/driller.py
  tests/test_cogitate.py
Labels: VERY IMPORTANT, help wanted

#79 Individual scoring
  .travis.yml
  Pipfile.lock
  data/raw_data_storage.json
  src/data_collection.py
  src/data_processor.py
  tests/test_data_processor.py
Labels: enhancement

#83 Remove duplicate main function and its running steps
  README.md
  src/data_collection.py
  src/data_processor.py
  tests/test_data_collection.py
  tests/test_data_processor.py
Labels: Quick Fix, documentation, duplicate

#86 Documentation
  README.md
  data/contributor_data.json
  src/cogitate.py
Labels: Quick Fix, documentation, important

#74 Overall eval/updating test cases
  .coveragerc
  .gitignore
  data/token.txt
  src/data_collection.py
  tests/test_issue_retrieval.py
Labels: enhancement, testing

#88 Update json_handler to handle inputs better, and remove pytest-sugar
  Pipfile
  src/json_handler.py
  tests/test_json_handler.py
Labels: Quick Fix, bug, enhancement, testing

#89 Merge Command line interface into Master
  .coveragerc
  .pylintrc
  Pipfile
  Pipfile.lock
  README.md
  data/contributor_data.json
  data/individual_metrics_storage.json
  data/raw_data_storage.json
  src/cogitate.py
  src/data_collection.py
  src/data_processor.py
  tests/test_cogitate.py
  tests/test_data_collection.py
Labels: Team Assignment, enhancement, important

#62 Web Interface
  Pipfile
  data/individual_metrics_storage.json
  src/cogitate.py
  src/web_interface.py
Labels: Team Assignment, enhancement
